# Generated by Django 3.1.3 on 2020-11-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=250)),
                ('stock', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=250)),
                ('picture', models.ImageField(default=None, upload_to='api/static/api')),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
